[package]
name = "busy_beaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.5.0"
regex = "1.10.4"
thiserror = "1.0.58"
# rug = "1.19.2"
